#!/bin/sh
echo "Precommit hook is running..."
ESLINT_MOBILE="$(git rev-parse --show-toplevel)/mobile/node_modules/.bin/eslint"
MOBILE_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '(^mobile)(.*)(ts$|tsx$)')
BACKEND_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '(^server)(.*)(ts$)')
PASS=true

echo "=============================================================================================================="
echo "Staged changes:"
echo '\t\033[32mMobile tracked files:\033[0m ' $MOBILE_FILES
echo '\t\033[32mBackend tracked files:\033[0m ' $BACKEND_FILES
echo "=============================================================================================================="
echo "Mobile validation started...";
for FILE in $MOBILE_FILES
do
	$ESLINT_MOBILE "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done
echo "=============================================================================================================="
echo "Backend validation started...";

for FILE in $BACKEND_FILES
do
	tslint --project server/tslint.json $FILE
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done
echo "=============================================================================================================="
echo "\nTypescript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?